export {default as Main} from './main'
export {default as Login} from './login'
export {default as Registr} from './registr'
export {default as Navbar} from './navbar'
export {default as ValidationError} from './validation-error'
export {default as ArticleDetail} from './article-detail'